version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: monthly
    time: "20:00"
  open-pull-requests-limit: 10
  versioning-strategy: increase-if-necessary
  ignore:
  - dependency-name: "@types/react-select"
    versions:
    - ">= 4.a, < 5"
  - dependency-name: webpack
    versions:
    - 5.21.2
    - 5.30.0
    - 5.33.2
  - dependency-name: webpack-cli
    versions:
    - 4.6.0
  - dependency-name: react-select
    versions:
    - 4.1.0
    - 4.3.0
  - dependency-name: ts-loader
    versions:
    - 8.0.16
    - 8.1.0
  - dependency-name: "@types/react-dom"
    versions:
    - 17.0.3
  - dependency-name: typescript
    versions:
    - 4.1.4
