name: CD

on:
  push:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up
      uses: actions/setup-node@v1
      with:
        node-version: '10.x'
    - name: Build
      run: |
        npm install
        npx webpack
        mkdir public
        cp -r ./dist ./public
        cp index.html ./public
    - name: Deploy
      uses: crazy-max/ghaction-github-pages@v1
      with:
        target_branch: gh-pages
        build_dir: public
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
