name: CI

on:
  push:
    pull_request:
      branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up
      uses: actions/setup-node@v1
      with:
        node-version: '10.x'
    - name: Build
      run: |
        npm install
        npx webpack
